# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Política de Datos"
email: datosabiertos@cdmx.gob.mx
description: "Política de Datos del Gobierno de la Ciudad de México."
direccion: "Dirección Ejecutiva de Política de Datos"
baseurl: "/politicadedatos"
url: ""
twitter_username: "GobCDMX"
github_username:  "GobCDMX"
color_theme:  "#00b140"
color_text:  "#fff"
language:  "es"

# Build settings
markdown: kramdown
permalink: /:title/
gems: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
